# Generated by Django 4.2.4 on 2023-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nation',
            field=models.CharField(default='', max_length=4),
        ),
    ]
